// <auto-generated />
namespace Clinika.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class a1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a1));
        
        string IMigrationMetadata.Id
        {
            get { return "201502120054484_a1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
